# Generated by Django 5.0.6 on 2024-07-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_url",
            field=models.CharField(
                default="https://canape.cdnflexcatering.com/themes/frontend/default/images/img-placeholder.png",
                max_length=700,
            ),
        ),
    ]
